version: '3.7'

services:
  cien-redis:
    image: redis:latest
    container_name: cien-redis
    hostname: cien-redis
    restart: always
    labels:
      - 'name=cien-redis'
      - 'mode=standalone'
    ports:
      - 6379:6379
